language: node_js
node_js:
  - "11"
script:
  - "npm install eslint"
  - "npm run lint"
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: "true"
  on:
    branch: master