language: node_js
before_deploy: |
  PKG_VERSION=$(node -p "require('./package.json').version")
  SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
  NPM_TAG="latest"

  if [[ "${PKG_VERSION}" = *-pre ]]; then
    NPM_TAG="next"
  fi
  echo "NPM_TAG=${NPM_TAG}"

  # If this is a pre-release version, give the package a unique version so we can publish it to npm
  # (as npm does not allow us to overwrite previously published packages)
  if [ "$NPM_TAG" == "next" ]; then
    UNIQUE_PKG_VERSION="${PKG_VERSION}.${SHORT_COMMIT_HASH}"
    npm version ${UNIQUE_PKG_VERSION}
    echo "Set package version to ${UNIQUE_PKG_VERSION}"
    cat package.json
  fi
deploy:
  skip_cleanup: true
  provider: npm
  email:
    secure: "$NPM_TOKEN"
  api_key:
    secure: "$NPM_TOKEN"
  on:
    branch: master
cache:
  directories:
  - node_modules
before_install:
- BAZEL_VERSION=0.28.0
- BAZEL_DEB="bazel_${BAZEL_VERSION}-linux-x86_64.deb"
- wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/${BAZEL_DEB} -O "${BAZEL_DEB}"
- sudo dpkg -i ${BAZEL_DEB}
- rm ${BAZEL_DEB}
install:
- npm install
script:
- "./travis-ci-build.sh"
